CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    street VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(50),
    zip VARCHAR(20),
    phone VARCHAR(30),
    email VARCHAR(150),
    -- Identity Path (Path B) fields - can be ignored for Path A
    account_level VARCHAR(20) DEFAULT 'BASIC',
    last_four_ssn VARCHAR(4),
    date_of_birth DATE,
    verification_date TIMESTAMP
);

-- Audit table for Identity Path (Path B) - can be ignored for Path A
CREATE TABLE IF NOT EXISTS verification_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL,
    attempted_at TIMESTAMP NOT NULL,
    success BOOLEAN NOT NULL,
    failure_reason VARCHAR(255),
    FOREIGN KEY (contact_id) REFERENCES contacts(id)
);
